services:
  postgres:
    image: postgres:17
    container_name: serviceops-postgres

    environment:
      POSTGRES_DB: serviceops
      POSTGRES_USER: serviceops
      POSTGRES_PASSWORD: serviceops

    ports:
      - "5433:5432"

    volumes:
      - serviceops-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U serviceops -d serviceops"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  serviceops-postgres-data:
